---
fail_fast: false
repos:
  - repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
    rev: fb9c7108c6c62aaf05441daa97ace3f40e840ac3
    hooks:
      - id: sops-encryption
        files: "(.*\\.sops\\.md)$"
