---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    age: "age1w68rvrv30t2xfm42ctr02vurav5222065pl03ys6ps5aklraq42s4jeyjl"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: "age1w68rvrv30t2xfm42ctr02vurav5222065pl03ys6ps5aklraq42s4jeyjl"
  - path_regex: ansible/.*\.sops\.ya?ml
    age: "age1w68rvrv30t2xfm42ctr02vurav5222065pl03ys6ps5aklraq42s4jeyjl"
  - path_regex: workflows/.*\.sops\.ya?ml
    age: "age1w68rvrv30t2xfm42ctr02vurav5222065pl03ys6ps5aklraq42s4jeyjl"
  - path_regex: .*\.sops\.md
    age: "age1w68rvrv30t2xfm42ctr02vurav5222065pl03ys6ps5aklraq42s4jeyjl"
stores:
  yaml:
    indent: 2
