---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  # Directories
  ANSIBLE_DIR: "{{.ROOT_DIR}}/ansible"
  BOOTSTRAP_DIR: "{{.ROOT_DIR}}/bootstrap"
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"
  PRIVATE_DIR: "{{.ROOT_DIR}}/.private"
  # Files
  BOOTSTRAP_ADDONS_FILE: "{{.BOOTSTRAP_DIR}}/vars/addons.yaml"
  BOOTSTRAP_CONFIG_FILE: "{{.BOOTSTRAP_DIR}}/vars/config.yaml"
  KUBECONFIG_FILE: "{{.ROOT_DIR}}/kubeconfig"
  MAKEJINJA_CONFIG_FILE: "{{.ROOT_DIR}}/makejinja.toml"
  PIP_REQUIREMENTS_FILE: "{{.ROOT_DIR}}/requirements.txt"
  SOPS_AGE_FILE: "{{.ROOT_DIR}}/age.key"
  # Binaries
  PYTHON_BIN: python3
  # Python
  PYTHONDONTWRITEBYTECODE: "1"

includes:
  ansible: .taskfiles/Ansible/Taskfile.yaml
  vs: .taskfiles/VolSync/Tasks.yaml

tasks:
  default: task -l
