---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-certificates
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: nginx-certificates
  dependsOn:
    - name: cert-manager-issuers
  interval: 1h
  path: ./kubernetes/apps/network/nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: network
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-external
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: nginx-external
  dependsOn:
    - name: nginx-certificates
  interval: 1h
  path: ./kubernetes/apps/network/nginx/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: network
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-internal
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: nginx-internal
  dependsOn:
    - name: nginx-certificates
  interval: 1h
  path: ./kubernetes/apps/network/nginx/internal
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
    namespace: flux-system
  targetNamespace: network
  wait: false
