---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-16-immich-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: store-k8s
  target:
    name: pg-16-immich-superuser-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .postgres_root_user }}"
        password: "{{ .postgres_root_pass }}"
        s3-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        s3-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: everything
    - extract:
        key: postgres-backup-minio-secret
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-16-immich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: store-k8s
  target:
    name: pg-16-immich-secret
    template:
      engineVersion: v2
      data:
        username: "{{ .immich_postgres_user }}"
        password: "{{ .immich_postgres_pass }}"
  dataFrom:
    - extract:
        key: everything
