---
apiVersion: ts.opentelekomcloud.com/v1alpha1
kind: TypesenseCluster
metadata:
  name: ty-neodb
  labels:
    app.kubernetes.io/name: typesense-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  image: typesense/typesense:29.1@sha256:2d9a7e348ce0de03a6061291023c54f83c47f0fa81f26b1b0d1110286e415b0c
  replicas: 1
  adminApiKey:
    name: typesense-neodb-secret
    namespace: database
  storage:
    size: 1Gi
    storageClassName: openebs-hostpath
