---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: thelounge
spec:
  chartRef:
    kind: OCIRepository
    name: thelounge
  interval: 1h
  values:
    controllers:
      thelounge:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/thelounge/thelounge
              tag: 4.5.2@sha256:bae46016776b0a18639dcaff69a103b3bbee9cbb40e86cd24fb278eccc6bac7b
            env:
              TZ: ${TIMEZONE}
              # https://github.com/thelounge/thelounge/issues/2656
              THELOUNGE_HOME: /config/thelounge
              LDAP_SEARCH_PASS:
                valueFrom:
                  secretKeyRef:
                    name: thelounge-secret
                    key: LDAP_SEARCH_PASS
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        primary: true
        controller: thelounge
        ports:
          http:
            primary: true
            port: 9000
    ingress:
      main:
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        # stateful data
        type: persistentVolumeClaim
        existingClaim: thelounge
        advancedMounts:
          thelounge:
            app:
              - path: /config/thelounge
      config-file:
        type: secret
        name: thelounge-secret
        globalMounts:
          - path: /config/thelounge/config.js
            subPath: config.js
            readOnly: true
