---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  chartRef:
    kind: OCIRepository
    name: radarr
  interval: 1h
  values:
    controllers:
      radarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: 6.4.4.10685@sha256:be53998a2d39cfa3c3315b70c7509a6a1f2a10c3aee9337653efc9f4c970430e
            env:
              TZ: ${TIMEZONE}
              RADARR__APP__INSTANCENAME: Radarr
              RADARR__APP__LAUNCHBROWSER: "False"
              RADARR__APP__THEME: dark
              RADARR__AUTH__METHOD: External
              RADARR__AUTH__REQUIRED: DisabledForLocalAddresses
              RADARR__LOG__ANALYTICSENABLED: "False"
              RADARR__LOG__DBENABLED: "False"
              RADARR__LOG__LEVEL: info
            envFrom: &envFrom
              - secretRef:
                  name: radarr-secret
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
              limits:
                memory: 2Gi
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.8@sha256:217c47c886965474f5c234b5a35ed008f53b39ea90a3088b31c0da98e1f9284d
            envFrom: *envFrom
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: "OnRootMismatch"
    service:
      main:
        controller: radarr
        ports:
          http:
            port: 7878
    ingress:
      main:
        className: internal
        annotations:
          auth.home.arpa/enabled: "true"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Radarr
          gethomepage.dev/icon: radarr.svg
          gethomepage.dev/description: Movie management
          gethomepage.dev/group: Media Mgmt
          gethomepage.dev/siteMonitor: &internalUrl "http://{{ .Release.Name }}.default.svc.cluster.local:7878"
          gethomepage.dev/widget.type: radarr
          gethomepage.dev/widget.url: *internalUrl
          gethomepage.dev/widget.key: "{{ `{{HOMEPAGE_VAR_RADARR_API_KEY}}` }}"
          gethomepage.dev/widget.enableQueue: "true"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: "/"
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: radarr
        advancedMounts:
          radarr:
            app:
              - path: /config
      movies:
        type: nfs
        server: nova.home.arpa
        path: /mnt/main/media/movies
        globalMounts:
          - path: /media/movies
      downloads:
        type: nfs
        server: nova.home.arpa
        path: /mnt/main/media/downloads
        globalMounts:
          - path: /media/downloads
