---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  chartRef:
    kind: OCIRepository
    name: longhorn
  interval: 1h
  values:
    csi:
      attacherReplicaCount: 1
      provisionerReplicaCount: 1
      resizerReplicaCount: 1
      snapshotterReplicaCount: 1
    defaultSettings:
      concurrentAutomaticEngineUpgradePerNodeLimit: "3"
      createDefaultDiskLabeledNodes: true
      defaultDataLocality: best-effort
      defaultLonghornStaticStorageClass: longhorn-static
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      nodeDrainPolicy: block-for-eviction-if-contains-last-replica
      orphanAutoDeletion: true
      replicaAutoBalance: best-effort
      storageMinimalAvailablePercentage: "5"
      storageReservedPercentageForDefaultDisk: "10"
      taintToleration: node-role.kubernetes.io/control-plane:NoSchedule
    ingress:
      annotations:
        auth.home.arpa/enabled: "true"
        gethomepage.dev/app: longhorn-ui
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn.png
        gethomepage.dev/name: Longhorn
      enabled: true
      host: longhorn.${SECRET_DOMAIN}
      ingressClassName: internal
      tls: true
    longhornDriver:
      tolerations: &tolerations
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
    longhornManager:
      tolerations: *tolerations
    longhornUI:
      replicas: 1
    metrics:
      serviceMonitor:
        enabled: true
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      defaultDataLocality: best-effort
