---
apiVersion: v1alpha1
kind: VolumeConfig
name: EPHEMERAL
provisioning:
  maxSize: 150GiB
---
apiVersion: v1alpha1
kind: UserVolumeConfig
name: extra
provisioning:
  diskSelector:
    match: system_disk
  grow: true
  minSize: 200GiB
  maxSize: 500GiB
