---
name: Reset Actionsflow Cache

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    name: Reset Actionsflow Cache
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run Actionsflow Clean
        uses: qlonik/actionsflow-action@8ffb42cf578a707a75e9f7b134e432914bf91559 # v3.1.0
        with:
          args: clean
          json-secrets: ${{ toJSON(secrets) }}
