---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
spec:
  storageClassName: nfs-minio
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Mi
  nfs:
    server: nova.home.arpa
    path: /mnt/main/appdata/minio
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
  claimRef:
    name: minio
    namespace: database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
spec:
  storageClassName: nfs-minio
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Mi
  volumeName: minio
